#ifndef H_CONSOLE_CONSTANTS
#define H_CONSOLE_CONSTANTS

#define CON_CONNECT 1
#define CON_DISCONNECT 2
#define CON_SET_VARIANCETHRESHOLD 3
#define CON_SET_MEASUREMENTINTERVAL 4
#define CON_SET_PINGTIMEOUT 5
#define CON_SET_MODE 6
#define CON_GET_VARIANCETHRESHOLD 7
#define CON_GET_MEASUREMENTINTERVAL 8
#define CON_GET_PINGTIMEOUT 9
#define CON_GET_MODE 10

#define CON_ACCEPT 100
#define CON_REJECT 101

#endif
